# Zsh config

# Use vi-mode
bindkey -v

typeset -g keymap="n/a"
typeset -g vi_ind=""
typeset -g viins_ind=""
typeset -g vicmd_ind=""

zle-refresh-prompt() {
  keymap=${KEYMAP}
  vi_ind="${${keymap/vicmd/$vicmd_ind}/(main|viins)/$viins_ind}"
  zle reset-prompt
}
zle -N zle-refresh-prompt

zle-keymap-select() {
  zle zle-refresh-prompt
}
zle -N zle-keymap-select

function zle-line-finish {
  zle zle-refresh-prompt
}
zle -N zle-line-finish

function zle-line-init {
  zle zle-refresh-prompt
}
zle -N zle-line-init


autoload -Uz compinit promptinit zmv colors && colors
setopt promptsubst
compinit
promptinit
source ~/dotfiles/shells/prompt_tukoo_setup
#prompt steeeff

zstyle ':completion::complete:*' use-cache 1

# Set key (esp. for Esc) delay to 1ms
KEYTIMEOUT=1

# ----------------------
# Git Aliases
# ----------------------
alias ga='git add'
alias gaa='git add .'
alias gaaa='git add -A'
alias gb='git branch'
alias gbd='git branch -d '
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gd='git diff'
alias gda='git diff HEAD'
alias gi='git init'
alias gl='git log'
alias glg='git log --graph --oneline --decorate --all'
alias gld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gm='git merge --no-ff'
alias gp='git pull'
alias gs='git status'
alias gss='git status -s'
alias gst='git stash'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstd='git stash drop'

# Search backwards and forwards with a pattern
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward
#
# # set up for insert mode too
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward

